# Generated by Django 4.0.8 on 2023-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='usd', max_length=200, unique=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Обменик', 'verbose_name_plural': 'Все Обменики'},
        ),
    ]
