# Generated by Django 4.0.8 on 2023-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencys_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchanger_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='currency',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='currencys',
            name='name',
            field=models.CharField(default='usd', max_length=20, unique=True, verbose_name='Валюта'),
        ),
    ]
