# Generated by Django 4.0.8 on 2023-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_exchanger_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='buy_eur',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='buy_usd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_eur',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_usd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
